#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xDBD2CE893E2D1C87 (cfeck@kde.org)
#
Name     : kdepim-apps-libs
Version  : 20.08.0
Release  : 28
URL      : https://download.kde.org/stable/release-service/20.08.0/src/kdepim-apps-libs-20.08.0.tar.xz
Source0  : https://download.kde.org/stable/release-service/20.08.0/src/kdepim-apps-libs-20.08.0.tar.xz
Source1  : https://download.kde.org/stable/release-service/20.08.0/src/kdepim-apps-libs-20.08.0.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: kdepim-apps-libs-data = %{version}-%{release}
Requires: kdepim-apps-libs-lib = %{version}-%{release}
Requires: kdepim-apps-libs-license = %{version}-%{release}
Requires: kdepim-apps-libs-locales = %{version}-%{release}
BuildRequires : akonadi-contacts-dev
BuildRequires : akonadi-dev
BuildRequires : boost-dev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : extra-cmake-modules-data
BuildRequires : gpgme-dev
BuildRequires : gpgme-extras
BuildRequires : grantlee-dev
BuildRequires : grantleetheme-dev
BuildRequires : kconfig-dev
BuildRequires : kconfigwidgets-dev
BuildRequires : kcontacts-dev
BuildRequires : kcoreaddons-dev
BuildRequires : ki18n-dev
BuildRequires : kimap-dev
BuildRequires : kimap-staticdev
BuildRequires : kio-dev
BuildRequires : kmime-dev
BuildRequires : libgpg-error-dev
BuildRequires : libkdepim-dev
BuildRequires : libkleo-dev
BuildRequires : pimcommon-dev
BuildRequires : qtbase-dev mesa-dev

%description
No detailed description available

%package data
Summary: data components for the kdepim-apps-libs package.
Group: Data

%description data
data components for the kdepim-apps-libs package.


%package dev
Summary: dev components for the kdepim-apps-libs package.
Group: Development
Requires: kdepim-apps-libs-lib = %{version}-%{release}
Requires: kdepim-apps-libs-data = %{version}-%{release}
Provides: kdepim-apps-libs-devel = %{version}-%{release}
Requires: kdepim-apps-libs = %{version}-%{release}

%description dev
dev components for the kdepim-apps-libs package.


%package lib
Summary: lib components for the kdepim-apps-libs package.
Group: Libraries
Requires: kdepim-apps-libs-data = %{version}-%{release}
Requires: kdepim-apps-libs-license = %{version}-%{release}

%description lib
lib components for the kdepim-apps-libs package.


%package license
Summary: license components for the kdepim-apps-libs package.
Group: Default

%description license
license components for the kdepim-apps-libs package.


%package locales
Summary: locales components for the kdepim-apps-libs package.
Group: Default

%description locales
locales components for the kdepim-apps-libs package.


%prep
%setup -q -n kdepim-apps-libs-20.08.0
cd %{_builddir}/kdepim-apps-libs-20.08.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1597734291
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1597734291
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/kdepim-apps-libs
cp %{_builddir}/kdepim-apps-libs-20.08.0/COPYING %{buildroot}/usr/share/package-licenses/kdepim-apps-libs/6a3bf83ab62e047649bdf91a17c9311737cede0f
cp %{_builddir}/kdepim-apps-libs-20.08.0/COPYING.LIB %{buildroot}/usr/share/package-licenses/kdepim-apps-libs/c914b1f9fc73a1ae187da32447bd161823f8b9e8
pushd clr-build
%make_install
popd
%find_lang libkaddressbookgrantlee
%find_lang libkaddressbookimportexport

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/qlogging-categories5/kdepim-apps-lib.categories

%files dev
%defattr(-,root,root,-)
/usr/include/KF5/KAddressBookImportExport/KAddressBookContactSelectionDialog
/usr/include/KF5/KAddressBookImportExport/KAddressBookContactSelectionWidget
/usr/include/KF5/KAddressBookImportExport/KAddressBookExportSelectionWidget
/usr/include/KF5/KAddressBookImportExport/KAddressBookImportExportContactList
/usr/include/KF5/KAddressBookImportExport/KAddressBookImportExportPlugin
/usr/include/KF5/KAddressBookImportExport/KAddressBookImportExportPluginInterface
/usr/include/KF5/KAddressBookImportExport/KAddressBookImportExportPluginManager
/usr/include/KF5/KaddressbookGrantlee/GrantleeContactFormatter
/usr/include/KF5/KaddressbookGrantlee/GrantleeContactGroupFormatter
/usr/include/KF5/KaddressbookGrantlee/GrantleeContactViewer
/usr/include/KF5/KaddressbookGrantlee/GrantleePrint
/usr/include/KF5/kaddressbookgrantlee/grantleecontactformatter.h
/usr/include/KF5/kaddressbookgrantlee/grantleecontactgroupformatter.h
/usr/include/KF5/kaddressbookgrantlee/grantleecontactviewer.h
/usr/include/KF5/kaddressbookgrantlee/grantleeprint.h
/usr/include/KF5/kaddressbookgrantlee/kaddressbook_grantlee_export.h
/usr/include/KF5/kaddressbookgrantlee_version.h
/usr/include/KF5/kaddressbookimportexport/kaddressbook_importexport_export.h
/usr/include/KF5/kaddressbookimportexport/kaddressbookcontactselectiondialog.h
/usr/include/KF5/kaddressbookimportexport/kaddressbookcontactselectionwidget.h
/usr/include/KF5/kaddressbookimportexport/kaddressbookexportselectionwidget.h
/usr/include/KF5/kaddressbookimportexport/kaddressbookimportexportcontactfields.h
/usr/include/KF5/kaddressbookimportexport/kaddressbookimportexportcontactlist.h
/usr/include/KF5/kaddressbookimportexport/kaddressbookimportexportplugin.h
/usr/include/KF5/kaddressbookimportexport/kaddressbookimportexportplugininterface.h
/usr/include/KF5/kaddressbookimportexport/kaddressbookimportexportpluginmanager.h
/usr/include/KF5/kaddressbookimportexport_version.h
/usr/lib64/cmake/KF5KaddressbookGrantlee/KF5KaddressbookGrantleeConfig.cmake
/usr/lib64/cmake/KF5KaddressbookGrantlee/KF5KaddressbookGrantleeConfigVersion.cmake
/usr/lib64/cmake/KF5KaddressbookGrantlee/KF5KaddressbookGrantleeTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KF5KaddressbookGrantlee/KF5KaddressbookGrantleeTargets.cmake
/usr/lib64/cmake/KF5KaddressbookImportExport/KF5KaddressbookImportExportConfig.cmake
/usr/lib64/cmake/KF5KaddressbookImportExport/KF5KaddressbookImportExportConfigVersion.cmake
/usr/lib64/cmake/KF5KaddressbookImportExport/KF5KaddressbookImportExportTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KF5KaddressbookImportExport/KF5KaddressbookImportExportTargets.cmake
/usr/lib64/libKF5KaddressbookGrantlee.so
/usr/lib64/libKF5KaddressbookImportExport.so
/usr/lib64/qt5/mkspecs/modules/qt_KaddressbookGrantlee.pri
/usr/lib64/qt5/mkspecs/modules/qt_KaddressbookImportExport.pri

%files lib
%defattr(-,root,root,-)
/usr/lib64/libKF5KaddressbookGrantlee.so.5
/usr/lib64/libKF5KaddressbookGrantlee.so.5.15.0
/usr/lib64/libKF5KaddressbookImportExport.so.5
/usr/lib64/libKF5KaddressbookImportExport.so.5.15.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/kdepim-apps-libs/6a3bf83ab62e047649bdf91a17c9311737cede0f
/usr/share/package-licenses/kdepim-apps-libs/c914b1f9fc73a1ae187da32447bd161823f8b9e8

%files locales -f libkaddressbookgrantlee.lang -f libkaddressbookimportexport.lang
%defattr(-,root,root,-)

